### ISSUE TITLE
Custom XML and JSON caching

### ISSUE THREAD

**Issue by Pantyhose-X** [rohitjakhar/Quizzon#12]
I want to allow custom import of XML and JSON to cache Quizz Web scraping
Network Use `XML` and `JSON`
No network Use `.kvtml` and `.apkg` import
All you need to do is mark the XML and JSON Web scraping rules

example  
518,279 questions, quiz
https://www.33iq.com/question/1.html        `question/1.html`       1 is the question page
https://www.33iq.com/question/518279.html

有若干根不均匀的绳子，每根绳子点燃一头的烧完时间是一个小时，用什么方法确定一段1小时15分钟的时间? （请回答最少需要几根绳子） There are a number of uneven ropes, each rope lit end of the burn out time is an hour, what method is used to determine a section of 1 hour and 15 minutes? (Please answer the minimum number of ropes needed)

- [x] A 1

- [x] B 2

- [ ] C 3

- [ ] D 4

**Comment by rohitjakhar** [comment]
Invalid Issue.
